version: '3.7'

services:
  iis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sql-server
    healthcheck:
      test: ["CMD", "iisreset", "/status"]
      interval: 10s
      timeout: 10s
      retries: 5

  sql-server:
    image: your-sql-image:tag  # Replace with your SQL Server image and tag
    environment:
      SA_PASSWORD: YourSAPassword
      ACCEPT_EULA: Y
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourSAPassword", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 10s
      retries: 5
