version: '3.7'

services:
  iis:
    image: docker.io/suvam754/projectwinserver-web-app:latest
    ports:
      - "80:80"
    depends_on:
      - sql-server

  sql-server:
    image: docker.io/suvam754/projectwinserver-sql-server
    ports:
      - "1433:1433"
    environment:
      sa_password: Bintu123
      ACCEPT_EULA: Y
      attach_dbs: '[{"dbName":"SampleDB","dbFiles":["C:\\temp\\sampledb.mdf","C:\\temp\\sampledb_log.ldf"]}]'
